name: test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: test
        run: |
          sh -ci "$(curl -fsSL https://storage.googleapis.com/flow-cli/install.sh)" -- v0.28.3
          npm i
          npm test
        env:
          FLOW_ADDRESS: '0x012345678abcdef'
          FLOW_PRIVATE_KEY: '0000000000000000000000000000000000000000000000000000000000000000'
